# Generated by Django 5.1.4 on 2024-12-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_solution', '0002_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostumerFeedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='costumer_feedbacks/')),
                ('position', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
