# Generated by Django 5.1.4 on 2024-12-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_solution', '0003_costumerfeedbacks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
